version: "3.8"
services:
    server:
        build: server/
        command: node ./server.js
        ports:
            - 8080:8080
    client:
        build: client/
        command: node ./client.js
        network_mode: host
        depends_on:
            - server
