version: "3.8"
services:
    server:
        build: server/
        ports:
        - 80:80
    client:
        build: client/
        command: node ./client.js
        network_mode: host
        depends_on:
            - server
